import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Target, Download, Share2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface InvestmentOutlookProps {
  recommendation: "Strong Buy" | "Moderate Buy" | "Hold" | "Moderate Sell" | "Strong Sell";
  confidence: number;
  summary: string;
}

export const InvestmentOutlook = ({
  recommendation,
  confidence,
  summary,
}: InvestmentOutlookProps) => {
  const { toast } = useToast();

  const getRecommendationStyle = () => {
    if (recommendation.includes("Buy")) {
      return "gradient-accent text-accent-foreground";
    } else if (recommendation === "Hold") {
      return "bg-warning text-warning-foreground";
    } else {
      return "bg-destructive text-destructive-foreground";
    }
  };

  const handleDownload = () => {
    toast({
      title: "Report Downloaded",
      description: "One-page investment summary saved as PDF",
    });
  };

  const handleShare = () => {
    toast({
      title: "Link Copied",
      description: "Share link copied to clipboard",
    });
  };

  return (
    <Card className="p-6 shadow-card hover:shadow-elevated transition-smooth">
      <div className="flex items-center gap-2 mb-6">
        <Target className="w-5 h-5 text-primary" />
        <h3 className="text-xl font-bold">Investment Outlook</h3>
      </div>

      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div className="space-y-2">
            <Badge className={`${getRecommendationStyle()} text-lg px-4 py-2`}>
              {recommendation}
            </Badge>
            <p className="text-sm text-muted-foreground">
              AI Confidence: <span className="font-semibold">{confidence}%</span>
            </p>
          </div>
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={handleShare}
              className="gap-2"
            >
              <Share2 className="w-4 h-4" />
              Share
            </Button>
            <Button
              variant="default"
              size="sm"
              onClick={handleDownload}
              className="gap-2 gradient-primary"
            >
              <Download className="w-4 h-4" />
              Download PDF
            </Button>
          </div>
        </div>

        <div className="p-4 rounded-lg bg-muted/50">
          <p className="text-sm leading-relaxed">{summary}</p>
        </div>

        <div className="pt-4 border-t space-y-2">
          <p className="text-xs text-muted-foreground">
            This analysis is generated by AI agents using automated financial data scraping and
            multi-source analysis. Investment decisions should be made after consulting with
            qualified financial advisors.
          </p>
        </div>
      </div>
    </Card>
  );
};
